### ISSUE TITLE
TODO release

### ISSUE THREAD

**Issue by clairezed** [sol-et-co/sol-et-co-website#1]
## Dev
- [ ] favicon
- [ ] update default pic
- [ ] responsive (equipe-card)
- [ ] sitemap ?
- [x] update content recompenses
- [x] update content competences + style
- [x] `is-active` menu link
- [x] design contact form
- [x] finish Qui sommes-nous (historique)
- [x] add pictures to equipe
- [x] manage conditional `has-background-white-ter` in `partial "page-header.html"` (https://stackoverflow.com/questions/45963231/in-a-hugo-partial-template-how-do-i-access-secondary-additional-parameters)
- [x] dynamic prestation and realisation subtitles in home page
- [x] change réalisations to `draft`

### en attente icono
- [x] add icons to prestation
- [x] add homepage picture

### en attente realisation
- [x] filter / sort réalisation byPrestation
- [ ] 'remonter' button in Prestations page

## Infra
- [x] forestry config recompenses
- [x] forestry uploads image processing
- [ ] NDD
- [ ] netlify contact form
